/// \file
#pragma once

#include "smdl/Common.h"

namespace smdl {

/// \addtogroup scene
/// \{

/// Unpack half-precision to single-precision.
[[nodiscard]] SMDL_EXPORT float unpackHalf(const void *ptr) noexcept;

class Emitter;

/// An image.
///
/// This is a generic container for image data held by the compiler
/// that is used at runtime by instances of `texture_2d` and/or
/// `texture_cube`.
///
/// Every level is stored in file order: row 0 is the top row of the
/// image, and `y` increases downward. Nothing here reorients the data.
/// MDL texture space is v-up, so the row is mirrored at lookup time by
/// `tex.smdl`, which is the only component that needs to know.
///
/// An image may carry a full mip chain down to 1x1, generated by
/// successive box-filtered halvings of the stored values. This is opt
/// in: `startLoad()` lays the chain out but generates nothing, and
/// `finishLoad()` generates it only if `requestMipLevels()` has asked
/// for it by then. The request is sticky and may arrive at any point,
/// even after `finishLoad()` has already run, because the chain memory
/// is reserved up front and generating into it cannot move level 0.
///
/// The chain is laid out unconditionally *unless* the load disallowed
/// it up front, i.e., `startLoad()` was passed `allowMipLevels` of
/// false. That is how a host turns mip levels off entirely, which
/// forfeits the late request in exchange for an allocation of exactly
/// the level 0 texels.
///
/// Mip levels are therefore a property of the *image*, while whether to
/// read them is a property of the `texture_2d` that references it: one
/// texture may sample the chain while another samples level 0 of the
/// same texels. This mirrors gamma, which is likewise applied per
/// lookup rather than baked into the stored texels, so that the same
/// image can back an sRGB and a linear texture. Chain generation is
/// gamma-agnostic for exactly that reason.
///
/// \note
/// The in-memory texel storage layout is deliberately unspecified and
/// may change between versions. The only supported way to read image
/// data is `fetch()`.
///
class SMDL_EXPORT Image final {
public:
  typedef void *(*image_malloc_t)(size_t);

  typedef void *(*image_calloc_t)(size_t, size_t);

  typedef void *(*image_realloc_t)(void *, size_t);

  typedef void (*image_free_t)(void *);

  /// The function to use to mimic `std::malloc`.
  static image_malloc_t image_malloc;

  /// The function to use to mimic `std::calloc`.
  static image_calloc_t image_calloc;

  /// The function to use to mimic `std::realloc`.
  static image_realloc_t image_realloc;

  /// The function to use to mimic `std::free`.
  static image_free_t image_free;

  /// The underlying format.
  enum Format : int {
    UINT8 = 1,   ///< 8-bit unsigned integer.
    UINT16 = 2,  ///< 16-bit unsigned integer.
    FLOAT16 = 3, ///< 16-bit floating point, AKA half precision.
    FLOAT32 = 4  ///< 32-bit floating point, AKA single precision.
  };

  Image() = default;

  /// Non-copyable, and non-movable!
  Image(const Image &) = delete;

public:
  /// Clear everything.
  void clear();

  /// \name Load API
  ///
  /// The API here is specifically tailored to the internal usage by
  /// the compiler. In particular, loading is factored into two stages,
  /// so that the computationally expensive portion can be done in
  /// parallel at the end of the compile!
  ///
  /// \{

  /// Try to start loading from the given file name.
  ///
  /// The implementation quickly scans for the format, size, and number of
  /// channels. This is enough information to allocate the `texels` buffer,
  /// which is understood to exist for the lifetime of the SMDL compiler.
  ///
  /// That being the case, the buffer pointer can be baked into JIT-compiled
  /// SMDL code, but we can defer loading the entire image until later, so
  /// that we can parallelize all of the image loads.
  ///
  /// The buffer is always laid out for the entire mip chain, whether or
  /// not anyone has asked for mip levels. That costs address space and
  /// not resident memory (the chain region is left untouched until it is
  /// generated), and it is what allows `requestMipLevels()` to be
  /// honored later without resizing a buffer whose pointer may already
  /// be baked into JIT-compiled code.
  ///
  /// \param[in] allowMipLevels
  /// May this image ever hold mip levels? If false, the buffer is laid
  /// out for level 0 alone and `requestMipLevels()` does nothing for the
  /// lifetime of this load. This is not the same as nobody having asked
  /// yet: it is the promise that nobody may, which is what lets the
  /// chain region go unreserved.
  ///
  [[nodiscard]] std::optional<Error>
  startLoad(const std::string &fileName, bool allowMipLevels = true) noexcept;

  /// Request mip levels, which `finishLoad()` generates.
  ///
  /// The request is sticky: an image is mipped if anything that
  /// references it ever asks, and asking twice is the same as asking
  /// once. It may be called before or after `finishLoad()`; in the
  /// latter case the next `finishLoad()` generates the chain.
  ///
  /// Call it after `startLoad()`, which clears the request along with
  /// everything else. If that load disallowed mip levels, this does
  /// nothing: the space they would occupy was never reserved.
  void requestMipLevels() noexcept {
    if (mMipLevelsAllowed) mMipLevelsRequested = true;
  }

  /// If `start_load()` was successful, finish loading the texels, then
  /// generate the mip chain if `requestMipLevels()` has asked for it and
  /// it has not been generated already.
  ///
  /// It is safe to call more than once. A decode failure leaves every
  /// level as well-defined zero texels.
  ///
  /// \throw std::runtime_error If anything fails.
  ///
  void finishLoad();

  /// \}

  /// Flip vertically.
  void flipVertically() noexcept;

public:
  /// Get the format.
  [[nodiscard]] Format getFormat() const noexcept { return mFormat; }

  /// Get the number of channels, must be 1, 2, or 4.
  [[nodiscard]] int getNumChannels() const noexcept { return mNumChannels; }

  /// Get the number of texels in X at the given mip level.
  [[nodiscard]] int getNumTexelsX(int level = 0) const noexcept {
    return level > 0 ? std::max(mNumTexelsX >> level, 1) : mNumTexelsX;
  }

  /// Get the number of texels in Y at the given mip level.
  [[nodiscard]] int getNumTexelsY(int level = 0) const noexcept {
    return level > 0 ? std::max(mNumTexelsY >> level, 1) : mNumTexelsY;
  }

  /// Get the number of mip levels the image holds, or will hold once
  /// `finishLoad()` has run. This is 1 unless `requestMipLevels()` has
  /// asked for the chain, and otherwise 1 for a 1x1 image, increasing by
  /// 1 for each doubling of the maximum extent, so the last level is
  /// always 1x1.
  [[nodiscard]] int getNumLevels() const noexcept {
    return mMipLevelsRequested ? mNumLevels : 1;
  }

  /// Get the texel size in bytes.
  ///
  /// \note
  /// This is necessarily the number of channels times the
  /// implied size of the format.
  ///
  [[nodiscard]] int getTexelSizeInBytes() const noexcept { return mTexelSize; }

  /// Get the total size of the texel memory in bytes, which counts every
  /// laid-out mip level whether or not it has been generated. So this is
  /// the level 0 texels alone if the load disallowed mip levels, and
  /// about one third more than that if it did not.
  [[nodiscard]] size_t getSizeInBytes() const noexcept { return mSizeInBytes; }

  /// Fetch texel at the given mip level.
  ///
  /// The valid runtime formats must contain 1, 2, or 4 channels of UINT8,
  /// UINT16, FLOAT16, or FLOAT32 channel type. The implementation converts all
  /// types to `float` by unsigned normalized integer conversion or by
  /// half-to-single precision conversion.
  ///
  /// Format  | Conversion
  /// --------|----------------------
  /// UINT8   | `value / 255.0f`
  /// UINT16  | `value / 65535.0f`
  /// FLOAT16 | `unpack_half(value)`
  /// FLOAT32 | `value`
  ///
  /// The implementation copies post-conversion channel values to
  /// the returned `float4` in order. Any channel not present is
  /// set to NaN.
  ///
  /// The coordinates must be within the extent of the requested level,
  /// i.e., `getNumTexelsX(level)` by `getNumTexelsY(level)`, and are in
  /// file order per the class doc comment above: `y` of 0 is the top row,
  /// not the bottom one.
  ///
  /// The level must be less than `getNumLevels()`. Levels beyond that are
  /// laid out but never written, so fetching one reads uninitialized
  /// memory: mip levels exist only after `finishLoad()`, and only if
  /// `requestMipLevels()` asked for them.
  ///
  [[nodiscard]] float4 fetch(int x, int y, int level = 0) const noexcept;

private:
  /// The `Emitter` bakes the texel buffer pointers into JIT-compiled
  /// code, so it is the one component that legitimately depends on
  /// the storage layout.
  friend class Emitter;

  /// The `Compiler` drops images the optimized module provably never
  /// reads, which needs the reservation address range and the private
  /// `abandonLoad()`.
  friend class Compiler;

  /// Get texels of the given mip level. Internal-only: the layout is
  /// unspecified.
  [[nodiscard]] auto getTexels(int level = 0) const noexcept
      -> const std::byte * {
    return mTexels ? mTexels.get() + mLevelOffsets[size_t(level)] : nullptr;
  }

  /// Abandon the load: forget any pending decode and release the texel
  /// reservation, keeping the probed metadata (extent, format, level
  /// layout). For the compiler's use once it has proven that no baked
  /// texel pointer survived into the optimized module; a later
  /// `finishLoad()` is a harmless no-op.
  void abandonLoad() noexcept;

  /// Generate mip levels 1 and up from level 0 by successive
  /// box-filtered halvings. Called at the end of `finishLoad()`.
  void generateMipLevels() noexcept;

  /// The number of mip levels actually written, i.e., holding texels.
  /// Unlike `getNumLevels()`, this waits for the generation itself, so
  /// it is what the routines that walk the storage must ask.
  [[nodiscard]] int getNumLevelsInMemory() const noexcept {
    return mMipLevelsGenerated ? mNumLevels : 1;
  }

  /// The format.
  Format mFormat{UINT8};

  /// The number of channels, must be 1, 2, or 4 for proper alignment.
  int mNumChannels{1};

  /// The number of texels in X.
  int mNumTexelsX{0};

  /// The number of texels in Y.
  int mNumTexelsY{0};

  /// The texel size in bytes.
  int mTexelSize{1};

  /// The number of mip levels in the layout, which is every level the
  /// extent implies whether or not they are asked for or generated, and
  /// 1 if they are not allowed at all.
  int mNumLevels{1};

  /// Are mip levels allowed? See `startLoad()`.
  bool mMipLevelsAllowed{true};

  /// Are mip levels requested? Sticky, see `requestMipLevels()`.
  bool mMipLevelsRequested{false};

  /// Are mip levels generated? I.e., do levels 1 and up hold texels?
  bool mMipLevelsGenerated{false};

  /// The byte offset of each mip level in `mTexels`. Always has
  /// `mNumLevels` entries, and entry 0 is always 0.
  std::vector<size_t> mLevelOffsets{0};

  /// The size of `mTexels` in bytes, i.e., of the entire layout.
  size_t mSizeInBytes{0};

  /// The texel memory, holding every mip level back to back.
  std::unique_ptr<std::byte[]> mTexels{};

  /// The function to finish loading the image.
  std::function<void()> mFinishLoad{};
};

/// Write an 8-bit-per-channel image to the given file name.
///
/// \param[in] fileName
/// The file name, which must end with a recognized extension. The
/// extension test is case-insensitive:
/// - `.png` writes PNG,
/// - `.jpg` or `.jpeg` writes JPEG at quality 90,
/// - `.bmp` writes BMP,
/// - `.tga` writes TGA,
/// - `.pgm` or `.ppm` writes binary PNM.
///
/// \param[in] numTexelsX
/// The number of texels in X, must be positive.
///
/// \param[in] numTexelsY
/// The number of texels in Y, must be positive.
///
/// \param[in] numChannels
/// The number of channels, must be 1, 2, 3, or 4.
///
/// \param[in] texels
/// The texels, understood to be tightly packed 8-bit channels in
/// row-major order starting from the top-left corner, i.e., channel
/// `c` of the texel at `(x, y)` is the byte at offset
/// `numChannels * (x + numTexelsX * y) + c`.
///
/// The PNG, JPEG, BMP, and TGA cases are handled by stb_image_write
/// with the usual channel interpretations: 1 is gray, 2 is gray and
/// alpha, 3 is RGB, and 4 is RGBA, where formats without alpha drop
/// the alpha channel. The PGM case writes only the first channel of
/// each texel, and the PPM case writes the first three channels of
/// each texel, zero-padding if there are fewer than three.
///
/// \note
/// The requirements on the dimensions, the channel count, and the
/// texel pointer are enforced by fatal sanity checks, not by
/// recoverable errors.
///
/// \return
/// `std::nullopt` if successful, or else an `Error` describing why
/// the image could not be written.
///
[[nodiscard]]
SMDL_EXPORT std::optional<Error>
write8bitImage(const std::string &fileName, int numTexelsX, int numTexelsY,
               int numChannels, const void *texels);

/// Write a single-precision floating point image to the given file name.
///
/// Unlike `write8bitImage()`, this preserves the full range of the values
/// it is given. It is the way to record physical radiance instead of a
/// display-referred approximation of it, so that the result can be
/// compared, denoised, or re-exposed after the fact.
///
/// \param[in] fileName
/// The file name, which must end with a recognized extension. The
/// extension test is case-insensitive:
/// - `.exr` writes OpenEXR with 32-bit channels and ZIP compression,
/// - `.hdr` writes Radiance RGBE.
///
/// \param[in] numTexelsX
/// The number of texels in X, must be positive.
///
/// \param[in] numTexelsY
/// The number of texels in Y, must be positive.
///
/// \param[in] numChannels
/// The number of channels, must be 1, 3, or 4. Note that 2 is not
/// allowed here even though `write8bitImage()` allows it, because
/// neither format has a sensible interpretation for it.
///
/// \param[in] texels
/// The texels, understood to be tightly packed single-precision
/// channels in row-major order starting from the top-left corner,
/// i.e., channel `c` of the texel at `(x, y)` is the float at index
/// `numChannels * (x + numTexelsX * y) + c`.
///
/// The channel interpretation is 1 for gray, 3 for RGB, and 4 for
/// RGBA. The Radiance case is lossy, as RGBE shares one exponent
/// between the color channels and drops alpha entirely; prefer
/// OpenEXR unless something downstream requires Radiance.
///
/// \note
/// The requirements on the dimensions, the channel count, and the
/// texel pointer are enforced by fatal sanity checks, not by
/// recoverable errors.
///
/// \return
/// `std::nullopt` if successful, or else an `Error` describing why
/// the image could not be written.
///
[[nodiscard]]
SMDL_EXPORT std::optional<Error>
writeFloatImage(const std::string &fileName, int numTexelsX, int numTexelsY,
                int numChannels, const float *texels);

/// \}

} // namespace smdl
