/// \file
#pragma once

#include "smdl/Common.h"

namespace smdl {

/// \addtogroup resource
/// \{

/// Unpack half-precision to single-precision.
[[nodiscard]] SMDL_EXPORT float unpackHalf(const void *ptr) noexcept;

/// An image.
///
/// This is a generic container for image data held by the compiler
/// that is used at runtime by instances of `texture_2d` and/or
/// `texture_cube`.
///
/// Every level is stored in file order: row 0 is the top row of the
/// image, and `y` increases downward. Nothing here reorients the data.
/// MDL texture space is v-up, so the row is mirrored at lookup time by
/// `tex.smdl`, which is the only component that needs to know.
///
/// An image may carry a full mip chain down to 1x1, generated by
/// successive box-filtered halvings of the stored values. This is opt
/// in, and the opting happens between the two halves of the load:
/// `startLoad()` only probes the file for its format and extent, then
/// `finishLoad()` allocates and decodes. So the allocation is exactly
/// the level 0 texels unless `requestMipLevels()` asked for the chain
/// first, and a request that arrives after `finishLoad()` is a contract
/// violation rather than a late arrival that can still be served.
///
/// The request is sticky and shared: an image is mipped if anything
/// that references it ever asks, so the several `texture_2d` values
/// over one file agree on one decoded image and one chain.
///
/// Mip levels are therefore a property of the *image*, while whether to
/// read them is a property of the `texture_2d` that references it: one
/// texture may sample the chain while another samples level 0 of the
/// same texels. This mirrors gamma, which is likewise applied per
/// lookup rather than baked into the stored texels, so that the same
/// image can back an sRGB and a linear texture. Chain generation is
/// gamma-agnostic for exactly that reason.
///
/// \note
/// The in-memory texel storage layout is deliberately unspecified and
/// may change between versions. The only supported way to read image
/// data is `fetch()`.
///
class SMDL_EXPORT Image final {
public:
  typedef void *(*image_malloc_t)(size_t);

  typedef void *(*image_calloc_t)(size_t, size_t);

  typedef void *(*image_realloc_t)(void *, size_t);

  typedef void (*image_free_t)(void *);

  /// The alignment of the texel memory. The compiler declares this on
  /// the symbol that names an image's texels, so an emitted access may
  /// assume it and the two must agree.
  static constexpr size_t TEXEL_ALIGNMENT{64};

  /// The function to use to mimic `std::malloc`.
  static image_malloc_t image_malloc;

  /// The function to use to mimic `std::calloc`.
  static image_calloc_t image_calloc;

  /// The function to use to mimic `std::realloc`.
  static image_realloc_t image_realloc;

  /// The function to use to mimic `std::free`.
  static image_free_t image_free;

  /// The underlying format.
  enum Format : int {
    UINT8 = 1,   ///< 8-bit unsigned integer.
    UINT16 = 2,  ///< 16-bit unsigned integer.
    FLOAT16 = 3, ///< 16-bit floating point, AKA half precision.
    FLOAT32 = 4  ///< 32-bit floating point, AKA single precision.
  };

  /// The reduction that builds each mip level from the level below it.
  enum MipFilter : int {
    /// The box filter: each texel is the mean of the texels it covers,
    /// so the chain is what prefiltered lookups want.
    MIP_MEAN = 0,
    /// The maximum: each texel bounds the bilinearly interpolated image
    /// over its footprint, so the chain is what a hierarchical march
    /// through a height field wants. Level 1 texel `(I, J)` is the
    /// maximum over level 0 texels `x` in `[2I - 1, 2I + 2]` and `y` in
    /// `[2J - 1, 2J + 2]`, that is, over the pair it covers plus the
    /// one-texel border whose bilinear patches straddle the pair's
    /// edges, wrapping at the image edges (an over-bound under the
    /// clamp and mirror wrap modes, never an under-bound); the last
    /// texel of an odd extent widens to cover the remainder; every
    /// further level is the plain maximum over the level below it. So
    /// the texel `(I, J)` of level `l` bounds the image over level 0
    /// texels `[I << l, (I + 1) << l)` per axis, the last texel of a
    /// level bounding through to the image edge. The maximum is taken
    /// per channel, each channel keeping a value that occurs in
    /// level 0.
    MIP_MAX = 1,
  };

  Image() = default;

  /// Non-copyable, and non-movable!
  Image(const Image &) = delete;

public:
  /// Clear everything.
  void clear();

  /// \name Load API
  ///
  /// The API here is specifically tailored to the internal usage by
  /// the compiler. In particular, loading is factored into two stages,
  /// so that the computationally expensive portion can be done in
  /// parallel at the end of the compile!
  ///
  /// \{

  /// Try to start loading from the given file name.
  ///
  /// The implementation quickly scans for the format, size, and number
  /// of channels, and nothing else: no texel memory is obtained here,
  /// and `getSizeInBytes()` is zero until `finishLoad()` runs. Deferring
  /// the decode is what lets many images load in parallel, and deferring
  /// the allocation with it is what lets `finishLoad()` ask for exactly
  /// the levels that were requested in the meantime.
  ///
  [[nodiscard]] std::optional<Error>
  startLoad(const std::string &fileName) noexcept;

  /// Request mip levels, which `finishLoad()` generates by `filter`.
  ///
  /// The request is sticky: an image is mipped if anything that
  /// references it ever asks, and asking twice is the same as asking
  /// once.
  ///
  /// An image holds one chain, so every request must agree on the
  /// filter: the first request decides, and a request for the other
  /// filter is refused so that the caller can say who asked for what.
  ///
  /// Call it between `startLoad()`, which clears the request along with
  /// everything else, and `finishLoad()`, which sizes the allocation to
  /// the answer. Asking afterward is a contract violation: the chain has
  /// nowhere to go, and moving the texels is not an option once they
  /// have an address.
  ///
  /// \return True unless a chain with the other filter was already
  /// requested, in which case nothing changes.
  bool requestMipLevels(MipFilter filter = MIP_MEAN) noexcept {
    SMDL_SANITY_CHECK_MSG(!mTexels,
                          "mip levels must be requested before 'finishLoad()'");
    if (mMipLevelsRequested && mMipFilter != filter) return false;
    mMipLevelsRequested = true;
    mMipFilter = filter;
    return true;
  }

  /// The filter of the mip chain, meaningful once `requestMipLevels()`
  /// has asked for one.
  [[nodiscard]] MipFilter getMipFilter() const noexcept { return mMipFilter; }

  /// If `startLoad()` was successful, allocate the texels for as many
  /// levels as `requestMipLevels()` has asked for, decode into level 0,
  /// and generate the rest of the chain.
  ///
  /// It is safe to call more than once; every call after the first one
  /// does nothing. A decode failure leaves every level as well-defined
  /// zero texels.
  ///
  /// \throw std::runtime_error If anything fails.
  ///
  void finishLoad();

  /// \}

  /// Flip vertically.
  void flipVertically() noexcept;

public:
  /// Get the format.
  [[nodiscard]] Format getFormat() const noexcept { return mFormat; }

  /// Get the number of channels, must be 1, 2, or 4.
  [[nodiscard]] int getNumChannels() const noexcept { return mNumChannels; }

  /// Get the number of texels in X at the given mip level.
  [[nodiscard]] int getNumTexelsX(int level = 0) const noexcept {
    return level > 0 ? std::max(mNumTexelsX >> level, 1) : mNumTexelsX;
  }

  /// Get the number of texels in Y at the given mip level.
  [[nodiscard]] int getNumTexelsY(int level = 0) const noexcept {
    return level > 0 ? std::max(mNumTexelsY >> level, 1) : mNumTexelsY;
  }

  /// Get the number of mip levels the image holds, or will hold once
  /// `finishLoad()` has run. This is 1 unless `requestMipLevels()` has
  /// asked for the chain, and otherwise 1 for a 1x1 image, increasing by
  /// 1 for each doubling of the maximum extent, so the last level is
  /// always 1x1.
  [[nodiscard]] int getNumLevels() const noexcept {
    return mMipLevelsRequested ? mNumLevels : 1;
  }

  /// Get the texel size in bytes.
  ///
  /// \note
  /// This is necessarily the number of channels times the
  /// implied size of the format.
  ///
  [[nodiscard]] int getTexelSizeInBytes() const noexcept { return mTexelSize; }

  /// Get the total size of the texel memory in bytes, which is zero
  /// until `finishLoad()` allocates it, then the level 0 texels alone,
  /// or about one third more than that when the chain was requested.
  [[nodiscard]] size_t getSizeInBytes() const noexcept { return mSizeInBytes; }

  /// Fetch texel at the given mip level.
  ///
  /// The valid runtime formats must contain 1, 2, or 4 channels of UINT8,
  /// UINT16, FLOAT16, or FLOAT32 channel type. The implementation converts all
  /// types to `float` by unsigned normalized integer conversion or by
  /// half-to-single precision conversion.
  ///
  /// Format  | Conversion
  /// --------|----------------------
  /// UINT8   | `value / 255.0f`
  /// UINT16  | `value / 65535.0f`
  /// FLOAT16 | `unpack_half(value)`
  /// FLOAT32 | `value`
  ///
  /// The implementation copies post-conversion channel values to
  /// the returned `float4` in order. Any channel not present is
  /// set to NaN.
  ///
  /// The coordinates must be within the extent of the requested level,
  /// i.e., `getNumTexelsX(level)` by `getNumTexelsY(level)`, and are in
  /// file order per the class doc comment above: `y` of 0 is the top row,
  /// not the bottom one.
  ///
  /// The level must be less than `getNumLevels()`, which is checked:
  /// levels beyond that are not allocated at all, because mip levels
  /// exist only after `finishLoad()`, and only if `requestMipLevels()`
  /// asked for them before it.
  ///
  [[nodiscard]] float4 fetch(int x, int y, int level = 0) const noexcept;

private:
  /// The `Compiler` drops images the optimized module provably never
  /// reads, and defines the texel address as a JIT symbol, which needs
  /// the private `abandonLoad()`, `hasPendingLoad()` and `getTexels()`.
  friend class Compiler;

  /// Frees the over-aligned texel memory obtained by `allocate()`.
  struct TexelDeleter final {
    void operator()(std::byte *texels) const noexcept {
      ::operator delete(texels, std::align_val_t(TEXEL_ALIGNMENT));
    }
  };

  /// Get texels of the given mip level. Internal-only: the layout is
  /// unspecified.
  [[nodiscard]] auto getTexels(int level = 0) const noexcept
      -> const std::byte * {
    return mTexels ? mTexels.get() + mLevelOffsets[size_t(level)] : nullptr;
  }

  /// Is there a decode still to run, i.e., did `startLoad()` succeed
  /// without `finishLoad()` or `abandonLoad()` having followed it?
  [[nodiscard]] bool hasPendingLoad() const noexcept {
    return bool(mFinishLoad);
  }

  /// Abandon the load: forget the pending decode, keeping the probed
  /// metadata (extent, format, level count). For the compiler's use once
  /// it has proven that nothing in the optimized module names the
  /// texels; `finishLoad()` then allocates nothing and decodes nothing.
  void abandonLoad() noexcept;

  /// Obtain the texel memory for as many levels as were requested, and
  /// zero level 0 so that a failed decode still reads as zero texels.
  /// Called by `finishLoad()`, which is the first point at which the
  /// level count is settled.
  void allocate();

  /// Generate mip levels 1 and up from level 0 by the requested
  /// `MipFilter`. Called at the end of `finishLoad()`.
  void generateMipLevels() noexcept;

  /// The `MIP_MEAN` reduction: successive box-filtered halvings.
  void generateMeanMipLevels() noexcept;

  /// The `MIP_MAX` reduction, see `MipFilter`.
  void generateMaxMipLevels() noexcept;

  /// The number of mip levels actually written, i.e., holding texels.
  /// Unlike `getNumLevels()`, this waits for the generation itself, so
  /// it is what the routines that walk the storage must ask.
  [[nodiscard]] int getNumLevelsInMemory() const noexcept {
    return mMipLevelsGenerated ? mNumLevels : 1;
  }

  /// The format.
  Format mFormat{UINT8};

  /// The number of channels, must be 1, 2, or 4 for proper alignment.
  int mNumChannels{1};

  /// The number of texels in X.
  int mNumTexelsX{0};

  /// The number of texels in Y.
  int mNumTexelsY{0};

  /// The texel size in bytes.
  int mTexelSize{1};

  /// The number of mip levels the extent implies, whether or not they
  /// are asked for, allocated or generated.
  int mNumLevels{1};

  /// Are mip levels requested? Sticky, see `requestMipLevels()`.
  bool mMipLevelsRequested{false};

  /// The filter of the requested chain, see `requestMipLevels()`.
  MipFilter mMipFilter{MIP_MEAN};

  /// Are mip levels generated? I.e., do levels 1 and up hold texels?
  bool mMipLevelsGenerated{false};

  /// The byte offset of each mip level in `mTexels`. Has one entry per
  /// allocated level, and entry 0 is always 0.
  std::vector<size_t> mLevelOffsets{0};

  /// The size of `mTexels` in bytes.
  size_t mSizeInBytes{0};

  /// The texel memory, holding every allocated mip level back to back.
  std::unique_ptr<std::byte[], TexelDeleter> mTexels{};

  /// The function to finish loading the image.
  std::function<void()> mFinishLoad{};
};

/// Write an 8-bit-per-channel image to the given file name.
///
/// \param[in] fileName
/// The file name, which must end with a recognized extension. The
/// extension test is case-insensitive:
/// - `.png` writes PNG,
/// - `.jpg` or `.jpeg` writes JPEG at quality 90,
/// - `.bmp` writes BMP,
/// - `.tga` writes TGA,
/// - `.pgm` or `.ppm` writes binary PNM.
///
/// \param[in] numTexelsX
/// The number of texels in X, must be positive.
///
/// \param[in] numTexelsY
/// The number of texels in Y, must be positive.
///
/// \param[in] numChannels
/// The number of channels, must be 1, 2, 3, or 4.
///
/// \param[in] texels
/// The texels, understood to be tightly packed 8-bit channels in
/// row-major order starting from the top-left corner, i.e., channel
/// `c` of the texel at `(x, y)` is the byte at offset
/// `numChannels * (x + numTexelsX * y) + c`.
///
/// The PNG, JPEG, BMP, and TGA cases are handled by stb_image_write
/// with the usual channel interpretations: 1 is gray, 2 is gray and
/// alpha, 3 is RGB, and 4 is RGBA, where formats without alpha drop
/// the alpha channel. The PGM case writes only the first channel of
/// each texel, and the PPM case writes the first three channels of
/// each texel, zero-padding if there are fewer than three.
///
/// \note
/// The requirements on the dimensions, the channel count, and the
/// texel pointer are enforced by fatal sanity checks, not by
/// recoverable errors.
///
/// \return
/// `std::nullopt` if successful, or else an `Error` describing why
/// the image could not be written.
///
[[nodiscard]]
SMDL_EXPORT std::optional<Error>
write8bitImage(const std::string &fileName, int numTexelsX, int numTexelsY,
               int numChannels, const void *texels);

/// Write a single-precision floating point image to the given file name.
///
/// Unlike `write8bitImage()`, this preserves the full range of the values
/// it is given. It is the way to record physical radiance instead of a
/// display-referred approximation of it, so that the result can be
/// compared, denoised, or re-exposed after the fact.
///
/// \param[in] fileName
/// The file name, which must end with a recognized extension. The
/// extension test is case-insensitive:
/// - `.exr` writes OpenEXR with 32-bit channels and ZIP compression,
/// - `.hdr` writes Radiance RGBE.
///
/// \param[in] numTexelsX
/// The number of texels in X, must be positive.
///
/// \param[in] numTexelsY
/// The number of texels in Y, must be positive.
///
/// \param[in] numChannels
/// The number of channels, must be 1, 3, or 4. Note that 2 is not
/// allowed here even though `write8bitImage()` allows it, because
/// neither format has a sensible interpretation for it.
///
/// \param[in] texels
/// The texels, understood to be tightly packed single-precision
/// channels in row-major order starting from the top-left corner,
/// i.e., channel `c` of the texel at `(x, y)` is the float at index
/// `numChannels * (x + numTexelsX * y) + c`.
///
/// The channel interpretation is 1 for gray, 3 for RGB, and 4 for
/// RGBA. The Radiance case is lossy, as RGBE shares one exponent
/// between the color channels and drops alpha entirely; prefer
/// OpenEXR unless something downstream requires Radiance.
///
/// \note
/// The requirements on the dimensions, the channel count, and the
/// texel pointer are enforced by fatal sanity checks, not by
/// recoverable errors.
///
/// \return
/// `std::nullopt` if successful, or else an `Error` describing why
/// the image could not be written.
///
[[nodiscard]]
SMDL_EXPORT std::optional<Error>
writeFloatImage(const std::string &fileName, int numTexelsX, int numTexelsY,
                int numChannels, const float *texels);

/// \}

} // namespace smdl
