= Language Design
:stylesheet: stylesheet.css
:source-highlighter: rouge
:rouge-style: molokai
:icons: font
:icon-set: fa
:toc: left

It is worth discussing the overall design of the SMDL implementation, 
because writing a compiler is hard, and understanding somebody else's 
compiler is harder.

[#guiding-principles]
== Guiding principles

* [x] The SMDL compiler *must be small, fast, and dependency free*. 
      It needs to integrate into rendering software and JIT compile materials
      at render time, and it cannot, e.g., spend 10 minutes on semantic 
      analysis and safety checks.
* [x] The SMDL compiler *must be compatible with MDL*. It needs to superimpose 
      specific interpretations on top of the underlying MDL semantics in 
      order to generate efficient material representations.

[CAUTION]
.Therefore
====
* [x] The language is *highly vectorized* with *no dynamic allocation*. 
* [x] The language is *unsafe* regardless of no dynamic allocation. Go
      ahead, dereference null!
* [x] The language uses *implicit generics and unions* as the
      foundation of behavior dispatch. 
====

[#the-repository]
== The repository

Let's discuss the code in the GitHub repo. Fundamentally, it uses 
https://cmake.org[CMake] to build two things: 

1. A {cpp} shared library `libSpectralMDL.so` built from code in `lib/` and
2. A {cpp} program `smdl` built from code in `src/` that 
   exposes the functionality of `libSpectralMDL.so` more conveniently.

[IMPORTANT]
.LLVM dependence
====
SMDL depends on LLVM _at build time_. However, the headers in `include/smdl/`
do not depend on LLVM headers and the relevant LLVM libraries are statically 
linked into `libSpectralMDL.so`. So a rendering program that uses SMDL doesn't 
depend on LLVM at all!
====

Everything interesting lives in the library. The `smdl` program is 
relatively minimal and is documented in the xref:command-line.adoc[Command Line
Interface] page, so we're not going to discuss it further here.

[#how-the-parser-works]
== How the parser works
The library uses a recursive descent parser to form an abstract syntax 
tree (AST). The parser is implemented in `lib/Parser.h` and `lib/Parser.cc`, 
and the AST is implemented in `lib/AST.h` and `lib/AST.cc`. The philosophy 
is to _just parse the damn string_. There is no lexer or tokenizer. 

[TIP]
.Memory management
====
The parser bump-allocates AST nodes from an instance of `llvm::BumpPtrAllocator` that 
persists until the compile is complete. This is efficient and prevents fragmentation.
Furthermore, AST nodes keep string views into the original source whenever possible 
to minimize string duplications.
====

[#how-the-compiler-works]
== How the compiler works

[#generics]
=== Generics

TODO
